[build]
rustflags = ["-Cforce-frame-pointers=yes"]

[target.x86_64-unknown-linux-gnu]
linker = "/usr/bin/clang"
rustflags = ["-Clink-arg=-fuse-ld=lld", "-Clink-arg=-Wl,--no-rosegment", "-Cforce-frame-pointers=yes", "-Cinline-threshold=0"]
